### ISSUE TITLE
Misleading name

### ISSUE THREAD

**Issue by Glandos** [dimkr/nss-tls#55]
Following the discussion on [debian-devel](https://lists.debian.org/debian-devel/2020/04/msg00283.html), it seems that `nss-tls` is misleading, since it use DNS-over-HTTPS, and not [DNS-over-TLS](https://en.wikipedia.org/wiki/DNS_over_TLS) which is a different protocol.

How could it possible to clarify this?

**Comment by dimkr** [comment]
When I chose the name, I didn't go for `nss-doh` because I wanted this solution to be able to support DoT as well, or at least, not to close the door on future DoT support. What DoT and DoH have in common, is TLS, hence `nss-tls`.

If the description is changed from "encrypted glibc name resolving library which uses DNS-over-HTTPS (DoH)" to "encrypted glibc name resolving library", it's no longer misleading.

**Comment by dimkr** [comment]
@Glandos ^

**Comment by kanru** [comment]
Hi, I filed the Debian "intent to package" bug. I think keeping the door open for DoT support is a very good reason for current naming. I'm looking forward to see DoT support being added :)

**Comment by Glandos** [comment]
OK, let's close this for now, and this issue will serve as reference for future questions if any.

Thanks for the answer!

**Comment by dimkr** [comment]
Thank you @kanru and @Glandos , please keep me in the loop if you need anything. Feel free to add a `debian/` in upstream.
